apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-internal
  namespace: {{ .Release.Namespace }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: esm-internal
    alb.ingress.kubernetes.io/group.order: {{ .Values.ingress.groupOrder | quote }}
    alb.ingress.kubernetes.io/healthcheck-path: /osticket/
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /osticket
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: 80
