apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.dbPasswordSecretId }}"
        objectType: "secretsmanager"
        objectAlias: "osticket-db-pw"
      - objectName: "{{ .Values.secrets.installSecretId }}"
        objectType: "secretsmanager"
        objectAlias: "osticket-install"
      - objectName: "{{ .Values.secrets.adminPasswordSecretId }}"
        objectType: "secretsmanager"
        objectAlias: "osticket-admin"
  secretObjects:
    - secretName: osticket-db
      type: Opaque
      data:
        - objectName: osticket-db-pw
          key: password
        - objectName: osticket-install
          key: install_secret
        - objectName: osticket-admin
          key: admin_password
