apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-efs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClassName }}
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "{{ .Values.persistence.efsId }}::{{ .Values.persistence.accessPointId }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: {{ .Values.persistence.storageClassName }}
  volumeName: {{ .Release.Name }}-efs-pv
