apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.dbPasswordSecretId }}"
        objectType: "secretsmanager"
        objectAlias: "odoo-db-pw"
  secretObjects:
    - secretName: odoo-db
      type: Opaque
      data:
        - objectName: odoo-db-pw
          key: password
