FROM odoo:17

# Copy OCA helpdesk addons needed by the restored database.
# Odoo official image includes /mnt/extra-addons in its default addons path.
COPY external_addons/helpdesk/helpdesk_mgmt /mnt/extra-addons/helpdesk_mgmt
COPY external_addons/helpdesk/helpdesk_mgmt_merge /mnt/extra-addons/helpdesk_mgmt_merge
COPY external_addons/helpdesk/helpdesk_mgmt_project /mnt/extra-addons/helpdesk_mgmt_project
COPY external_addons/helpdesk/helpdesk_mgmt_sale /mnt/extra-addons/helpdesk_mgmt_sale
COPY external_addons/helpdesk/helpdesk_ticket_related /mnt/extra-addons/helpdesk_ticket_related
COPY external_addons/helpdesk/helpdesk_type /mnt/extra-addons/helpdesk_type
