apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-private
  namespace: odoo-private
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: odoo-private
  template:
    metadata:
      labels:
        app: odoo-private
    spec:
      containers:
        - name: odoo
          image: "__ODOO_IMAGE__"
          imagePullPolicy: IfNotPresent
          args:
            - "--database=__ODOO_DB_NAME__"
            - "--db-filter=^__ODOO_DB_NAME__$"
            - "--init=base"
            - "--without-demo=all"
          ports:
            - containerPort: 8069
          env:
            - name: HOST
              value: "__ODOO_DB_HOST__"
            - name: PORT
              value: "5432"
            - name: USER
              value: "__ODOO_DB_USER__"
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: odoo-db
                  key: password
            - name: PGSSLMODE
              value: require
          volumeMounts:
            - name: odoo-data
              mountPath: /var/lib/odoo
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 2Gi
      volumes:
        - name: odoo-data
          persistentVolumeClaim:
            claimName: odoo-pvc
