apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.dbPasswordSecretId }}"
        objectType: "secretsmanager"
        objectAlias: "moodle-db-pw"
      - objectName: "{{ .Values.secrets.adminPasswordSecretId }}"
        objectType: "secretsmanager"
        objectAlias: "moodle-admin-pw"
  secretObjects:
    - secretName: moodle-db
      type: Opaque
      data:
        - objectName: moodle-db-pw
          key: password
        - objectName: moodle-admin-pw
          key: admin_password
