apiVersion: v1
kind: Namespace
metadata:
  name: odoo-public
  labels:
    app.kubernetes.io/part-of: esm
---
apiVersion: v1
kind: Namespace
metadata:
  name: odoo-private
  labels:
    app.kubernetes.io/part-of: esm
---
apiVersion: v1
kind: Namespace
metadata:
  name: moodle-private
  labels:
    app.kubernetes.io/part-of: esm
---
apiVersion: v1
kind: Namespace
metadata:
  name: osticket-private
  labels:
    app.kubernetes.io/part-of: esm
