apiVersion: v1
kind: Secret
metadata:
  name: odoo-db
  namespace: odoo-public
type: Opaque
stringData:
  password: "__ODOO_DB_PASSWORD__"
---
apiVersion: v1
kind: Secret
metadata:
  name: odoo-db
  namespace: odoo-private
type: Opaque
stringData:
  password: "__ODOO_DB_PASSWORD__"
---
apiVersion: v1
kind: Secret
metadata:
  name: moodle-db
  namespace: moodle-private
type: Opaque
stringData:
  password: "__MOODLE_DB_PASSWORD__"
  admin_password: "__MOODLE_ADMIN_PASSWORD__"
---
apiVersion: v1
kind: Secret
metadata:
  name: osticket-db
  namespace: osticket-private
type: Opaque
stringData:
  password: "__OSTICKET_DB_PASSWORD__"
  install_secret: "__OSTICKET_INSTALL_SECRET__"
  admin_password: "__OSTICKET_ADMIN_PASSWORD__"
