apiVersion: v1
kind: Secret
metadata:
  name: odoo-db
  namespace: odoo-public
type: Opaque
stringData:
  password: "__ODOO_DB_PASSWORD__"
---
apiVersion: v1
kind: Secret
metadata:
  name: odoo-db
  namespace: odoo-private
type: Opaque
stringData:
  password: "__ODOO_DB_PASSWORD__"
---
apiVersion: v1
kind: Secret
metadata:
  name: moodle-db
  namespace: moodle-private
type: Opaque
stringData:
  password: "__MOODLE_DB_PASSWORD__"
---
apiVersion: v1
kind: Secret
metadata:
  name: osticket-db
  namespace: osticket-private
type: Opaque
stringData:
  password: "__OSTICKET_DB_PASSWORD__"
