apiVersion: v1
kind: Secret
metadata:
  name: odoo-db
  namespace: esm
type: Opaque
stringData:
  password: "ChangeMeSecurePassword123!"
---
apiVersion: v1
kind: Secret
metadata:
  name: moodle-db
  namespace: esm
type: Opaque
stringData:
  password: "ChangeMeSecurePassword456!"
