[options]
admin_passwd = admin
db_host = db
db_port = 5432
db_user = odoo17
db_password = odoo17
db_name = odoo
addons_path = /mnt/odoo-src/odoo/addons,/mnt/odoo-src/addons,/mnt/oca-helpdesk
data_dir = /var/lib/odoo
http_port = 8069
gevent_port = 8072
proxy_mode = False
list_db = True
