apiVersion: v1
kind: Service
metadata:
  name: moodle
  namespace: moodle-private
spec:
  type: NodePort
  selector:
    app: moodle
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30082
      protocol: TCP
