apiVersion: apps/v1
kind: Deployment
metadata:
  name: osticket
  namespace: osticket-private
spec:
  replicas: 3
  selector:
    matchLabels:
      app: osticket
  template:
    metadata:
      labels:
        app: osticket
    spec:
      containers:
        - name: osticket
          image: "__OSTICKET_IMAGE__"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              value: "__OSTICKET_DB_HOST__"
            - name: MYSQL_DATABASE
              value: "__OSTICKET_DB_NAME__"
            - name: MYSQL_USER
              value: "__OSTICKET_DB_USER__"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: osticket-db
                  key: password
            - name: INSTALL_SECRET
              valueFrom:
                secretKeyRef:
                  name: osticket-db
                  key: install_secret
            - name: INSTALL_NAME
              value: "__OSTICKET_INSTALL_NAME__"
            - name: INSTALL_URL
              value: "__OSTICKET_INSTALL_URL__"
            - name: INSTALL_EMAIL
              value: "__OSTICKET_INSTALL_EMAIL__"
            - name: ADMIN_FIRSTNAME
              value: "__OSTICKET_ADMIN_FIRSTNAME__"
            - name: ADMIN_LASTNAME
              value: "__OSTICKET_ADMIN_LASTNAME__"
            - name: ADMIN_EMAIL
              value: "__OSTICKET_ADMIN_EMAIL__"
            - name: ADMIN_USERNAME
              value: "__OSTICKET_ADMIN_USERNAME__"
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: osticket-db
                  key: admin_password
            - name: CRON_INTERVAL
              value: "__OSTICKET_CRON_INTERVAL__"
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 90
            periodSeconds: 20
