apiVersion: apps/v1
kind: Deployment
metadata:
  name: osticket
  namespace: osticket-private
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osticket
  template:
    metadata:
      labels:
        app: osticket
    spec:
      containers:
        - name: osticket
          image: campbellsoftwaresolutions/osticket:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              value: "__OSTICKET_DB_HOST__"
            - name: MYSQL_DATABASE
              value: "__OSTICKET_DB_NAME__"
            - name: MYSQL_USER
              value: "__OSTICKET_DB_USER__"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: osticket-db
                  key: password
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 90
            periodSeconds: 20
