apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-efs-public-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-static-public
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "fs-09c553698a3e9086e::fsap-0aa7ada652a747b4d"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-public-pvc
  namespace: odoo-public
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: efs-static-public
  volumeName: odoo-efs-public-pv
