# ==============================================================================
# Moodle — Production Overlay
# ==============================================================================

image:
  tag: "latest"

db:
  host: "esm-enterprise-prod-moodle.c9asmcmsm7pz.ap-southeast-1.rds.amazonaws.com"
  name: "moodledb"
  user: "moodle_admin"

persistence:
  efsId: "fs-09adfe24a1c9304eb"
  accessPointId: "fsap-0e0303c8316fbcec6"

moodle:
  url: "http://moodle.internal.esm.local"
  adminUser: ""   # set your Moodle admin username
  adminEmail: ""  # set your Moodle admin e-mail

serviceAccount:
  irsaRoleArn: "arn:aws:iam::990521646880:role/esm-enterprise-prod-moodle-irsa"

secrets:
  dbPasswordSecretId: "esm/prod/moodle-db-password"
  adminPasswordSecretId: "esm/prod/moodle-admin-password"
